error_on_failure: false

error_on_warning: false

vignettes:
  active: true
  flesch-kincaid:
    active: true
    thresholds:
      poor_readbility:
        active: true
        warn: 50
        fail: 40
        approval: "high"
  length:
    active: true
    thresholds:
      too_long:
        active: true
        warn: 2000
        fail: 3000
        approval: "low"
      too_short:
        active: true
        warn: 500
        fail: 200
        approval: "high"
  problem_words:
    active: false
  image_alt_text:
    active: false

functions:
  active: true
  exports_without_examples:
    active: true
    missing_examples:
      active: true
      warn: 1
      fail: 99999
      approval: "low"
